### ISSUE TITLE
[Bug]: Script task fail on windows. Quote escaping related.

### ISSUE THREAD

**Issue by lionelhorn** [rrweb-io/rrweb#1231]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

from source

### Expected Behavior

Able to follow the contributing guide. https://github.com/rrweb-io/rrweb#contribute-guide without errors.

### Actual Behavior

Step 3. Run yarn dev in the root to get auto-building for all the sub-packages whenever you modify anything.
=> Fails with import error. 

### Steps to Reproduce

Do step 1 to 3.

System is windows. Packages are not build and /dist/ aren't present. Then the yarn-dev fails.

May be related to npm tasks and quotes on windows.

Replacing https://github.com/rrweb-io/rrweb/blob/a6ce7182ce59da8a565b12f7dfcb87eb10ec7ca4/package.json#L39 with
```
    "build:all": "yarn run concurrently --success=all -r -m=1 \"yarn workspaces-to-typescript-project-references\" \"yarn turbo run prepublish\""
```

seems to work.

Similar but a bit different from https://github.com/rrweb-io/rrweb/issues/12

### Additional Information

```
rrweb:dev: [!] Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev: Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev:
```

```yarn run v1.23.0-20220130.1630
$ yarn turbo run dev
$ C:\PROG\_chrome-exts\rrweb-repro\node_modules\.bin\turbo run dev
• Packages in scope: @rrweb/types, @rrweb/web-extension, rrdom, rrdom-nodejs, rrvideo, rrweb, rrweb-player, rrweb-snapshot
• Running dev in 8 packages
rrdom:dev: cache miss, executing 5e8ecd9c81071dd5
rrdom-nodejs:dev: cache miss, executing 8ba21a08b210415b
@rrweb/types:dev: cache miss, executing d046f08a31615a37
rrweb-player:dev: cache miss, executing 493e3a51d868ebfc
rrweb-snapshot:dev: cache miss, executing 0f4cc68d0dfaf59c
rrweb:dev: cache miss, executing 6bdee3ea250f9b0b
rrweb-player:dev: $ rollup -c -w
@rrweb/types:dev: $ vite
rrweb:dev: $ yarn bundle:browser --watch
rrdom:dev: $ rollup -c -w
rrdom-nodejs:dev: $ rollup -c -w
rrweb-snapshot:dev: $ yarn bundle:es-only --watch
rrweb:dev: $ cross-env BROWSER_ONLY=true rollup --config --watch
rrweb-snapshot:dev: $ cross-env ES_ONLY=true rollup --config --watch
rrweb-snapshot:dev: rollup v2.53.3
rrweb-snapshot:dev: bundles ./src/index.ts → es\rrweb-snapshot.js...
rrdom:dev: rollup v2.60.2
rrdom:dev: bundles ./src/index.ts → es\rrdom.js...
rrdom-nodejs:dev: rollup v2.60.2
rrdom-nodejs:dev: bundles ./src/index.ts → es\rrdom-nodejs.js...
rrweb:dev: rollup v2.68.0
rrweb:dev: bundles ./src/index.ts → dist\rrweb.js...
rrweb:dev: [!] Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev: Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev:
rrweb:dev: bundles ./src/entries/all.ts → dist\rrweb-all.js...
rrweb:dev: [!] Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev: Error: Could not load C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js (imported by src\index.ts): ENOENT: no such file or directory, open 'C:\PROG\_chrome-exts\rrweb-repro\packages\types\dist\types.js'
rrweb:dev:
rrweb:dev: bundles ./src/plugins/console/record/index.ts → dist\plugins\console-record.js...
rrweb:dev: (!) Unresolved dependencies
rrweb:dev: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
rrweb:dev: rrweb-snapshot (imported by src\record\index.ts, src\utils.ts, src\replay\index.ts, src\record\iframe-manager.ts, src\record\obse
rver.ts, src\record\stylesheet-manager.ts, src\record\shadow-dom-manager.ts, src\replay\index.ts, src\utils.ts, src\record\index.ts, src\rec
ord\iframe-manager.ts, src\record\mutation.ts, src\record\observer.ts, src\record\stylesheet-manager.ts, src\record\shadow-dom-manager.ts, src\record\mutation.ts, src\utils.ts)
rrweb:dev: rrdom (imported by src\replay\index.ts, src\replay\index.ts)
rrweb:dev: created dist\plugins\console-record.js in 985ms
rrweb:dev: bundles ./src/plugins/canvas-webrtc/record/index.ts → dist\plugins\canvas-webrtc-record.js...
rrweb:dev: created dist\plugins\canvas-webrtc-record.js in 564ms
rrweb:dev: bundles ./src/plugins/canvas-webrtc/replay/index.ts → dist\plugins\canvas-webrtc-replay.js...
rrweb:dev: created dist\plugins\canvas-webrtc-replay.js in 182ms
rrweb-player:dev: rollup v2.71.1
rrweb-player:dev: bundles src/main.ts → public/bundle.js...
rrweb-player:dev: [!] (plugin commonjs--resolver) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrweb-player/src/main.ts(1,36): semantic error TS2307: Cannot find module '@rrweb/types' or its corresponding type declarations.
rrweb-player:dev: src/main.ts
rrweb-player:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrweb-player/src/main.ts(1,36): semantic error TS2307: Cannot find module '@rrweb/types' or its corresponding type declarations.
rrweb-player:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\packages\rrweb-player\node_modules\rollup\dist\shared\rollup.js:198:30)    
rrweb-player:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\packages\rrweb-player\node_modules\rollup\dist\shared\rollup.js:21902:12)
rrweb-player:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\packages\rrweb-player\node_modules\rollup\dist\shared\rollup.js:22625:20)
rrweb-player:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\packages\rrweb-player\node_modules\rollup\dist\shared\rollup.js:22079:42)
rrweb-player:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
rrweb-player:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrweb-player:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)
rrweb-player:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrweb-player:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
rrweb-player:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)      
rrweb-player:dev:
@rrweb/types:dev: Port 5173 is in use, trying another one...
@rrweb/types:dev:
@rrweb/types:dev:   VITE v3.2.2  ready in 27594 ms
@rrweb/types:dev:
@rrweb/types:dev:   ➜  Local:   http://localhost:5174/
@rrweb/types:dev:   ➜  Network: use --host to expose
@rrweb/types:dev: (!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
rrdom:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev: src\index.ts
rrdom-nodejs:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev: src\document-nodejs.ts
rrdom:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)  
rrdom:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)  
rrdom:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)   
rrdom:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)
rrdom:dev:
rrdom:dev: bundles ./src/index.ts → dist\rrdom.js...
rrdom-nodejs:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom-nodejs:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom-nodejs:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
rrdom-nodejs:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom-nodejs:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)
rrdom-nodejs:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom-nodejs:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
rrdom-nodejs:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)      
rrdom-nodejs:dev:
rrdom-nodejs:dev: bundles ./src/document-nodejs.ts → es\document-nodejs.js...
rrweb-snapshot:dev: created es\rrweb-snapshot.js in 19.5s
rrdom-nodejs:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev: src\document-nodejs.ts
rrdom-nodejs:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom-nodejs:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom-nodejs:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
rrdom-nodejs:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom-nodejs:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)
rrdom-nodejs:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom-nodejs:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
rrdom-nodejs:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)      
rrdom-nodejs:dev:
rrdom-nodejs:dev: bundles ./src/index.ts → lib\rrdom-nodejs.cjs...
rrdom:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev: src\index.ts
rrdom:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)  
rrdom:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)  
rrdom:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)   
rrdom:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)
rrdom:dev:
rrdom:dev: bundles ./src/index.ts → dist\rrdom.min.js...
rrdom-nodejs:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev: src\document-nodejs.ts
rrdom-nodejs:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom-nodejs/src/document-nodejs.ts(2,40): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom-nodejs:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom-nodejs:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom-nodejs:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom-nodejs:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
rrdom-nodejs:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom-nodejs:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)
rrdom-nodejs:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom-nodejs:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
rrdom-nodejs:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)      
rrdom-nodejs:dev:
rrdom-nodejs:dev: bundles ./src/index.ts → es\rrdom-nodejs.min.js...
rrdom:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev: src\index.ts
rrdom:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
rrdom:dev:     at RollupContext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)  
rrdom:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)  
rrdom:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)   
rrdom:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)
rrdom:dev:
rrdom:dev: bundles ./src/index.ts → lib\rrdom.cjs...
rrdom:dev: [!] (plugin rpt2) Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev: src\index.ts
rrdom:dev: Error: C:/PROG/_chrome-exts/rrweb-repro/packages/rrdom/src/index.ts(4,8): semantic error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.
rrdom:dev:     at error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:158:30)
rrdom:dev:     at throwPluginError (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21793:12)
rrdom:dev:     at Object.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:22497:20)
Terminate batch job (Y/N)? ject.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup\dist\shared\rollup.js:21969:38)
C:\PROG\_chrome-exts\rrweb-repro>ntext.error (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\rollupcontext.ts:37:18)
rrdom-nodejs:dev:     at C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:41:11
rrdom-nodejs:dev:     at arrayEach (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:530:11)
rrdom-nodejs:dev:     at Function._.each [as forEach] (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\node_modules\lodash\lodash.js:9410:14)
rrdom-nodejs:dev:     at printDiagnostics (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\print-diagnostics.ts:9:2)
rrdom-nodejs:dev:     at Object.transform (C:\PROG\_chrome-exts\rrweb-repro\node_modules\rollup-plugin-typescript2\src\index.ts:244:5)
rrdom-nodejs:dev:
```

**Comment by eoghanmurray** [comment]
Could you check if swapping the quotes as follows works?

```
    "build:all": 'yarn run concurrently --success=all -r -m=1 "yarn workspaces-to-typescript-project-references" "yarn turbo run prepublish"'
```

(that just seems cleaner to my mind anyhow)

We could update all commands in package.json to use this style of quoting in the right hand side.

I'll then have to check whether there's any linting tools that update or complain about the JSON.

**Comment by Juice10** [comment]
> Could you check if swapping the quotes as follows works?
> 
> ```
>     "build:all": 'yarn run concurrently --success=all -r -m=1 "yarn workspaces-to-typescript-project-references" "yarn turbo run prepublish"'
> ```
> 
> (that just seems cleaner to my mind anyhow)
> 
> We could update all commands in package.json to use this style of quoting in the right hand side.
> 
> I'll then have to check whether there's any linting tools that update or complain about the JSON.

Unfortunately JSON doesn't allow single quotes :/ so we can't do this for package.json
