### ISSUE TITLE
when use repl, fail to replay 

### ISSUE THREAD

**Issue by Derkin** [rrweb-io/rrweb#205]
./src/index.ts → dist/rrweb.min.js...
created dist/rrweb.min.js in 2.6s
? Enter the url you want to record, e.g https://react-redux.realworld.io:  https://www.baidu.com/
Going to open https://www.baidu.com/...
Ready to record. You can do any interaction on the page.
? Once you want to finish the recording, enter 'y' to start replay:  Yes
Recorded 2 events
? Persistently store these recorded events? (Y/n) Error: ENOENT: no such file or directory, open '/Users/galaxy/codes/github/rrweb/dist/rrweb.min.css'
  -- ASYNC --
    at Frame.<anonymous> (/Users/galaxy/codes/github/rrweb/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addStyleTag (/Users/galaxy/codes/github/rrweb/node_modules/puppeteer/lib/Page.js:431:29)
    at Page.<anonymous> (/Users/galaxy/codes/github/rrweb/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/galaxy/codes/github/rrweb/scripts/repl.ts:132:16
    at step (/Users/galaxy/codes/github/rrweb/scripts/repl.ts:33:23)
    at Object.next (/Users/galaxy/codes/github/rrweb/scripts/repl.ts:14:53)
    at fulfilled (/Users/galaxy/codes/github/rrweb/scripts/repl.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/galaxy/codes/github/rrweb/dist/rrweb.min.css'
}

**Comment by Yuyz0112** [comment]
@Derkin Thanks for the report! I believe it has been fixed in the latest commit.
