### ISSUE TITLE
npm run repl error

### ISSUE THREAD

**Issue by cquirosj** [rrweb-io/rrweb#275]
Hi,

When I run 

**npm run repl** 

The chromium-browser appears briefly, it shows a blank page then closes and I get the following error:

rrweb git:(master) npm run repl

> rrweb@0.8.5 repl /Users/christianquiros/Documents/learning/rrweb
> npm run bundle:browser && cross-env TS_NODE_CACHE=false TS_NODE_FILES=true ts-node scripts/repl.t

> rrweb@0.8.5 bundle:browser /Users/christianquiros/Documents/learning/rrweb
> cross-env BROWSER_ONLY=true rollup --config

./src/index.ts → dist/rrweb.min.js...
created dist/rrweb.min.js in 2.9s
? Enter the url you want to record, e.g https://react-redux.realworld.io:  https://github.com
Going to open https://github.com...
Error: Protocol error (Page.navigate): Target closed.
    at /Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/christianquiros/Documents/learning/rrweb/scripts/repl.ts:87:16
  -- ASYNC --
    at Frame.<anonymous> (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/christianquiros/Documents/learning/rrweb/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/christianquiros/Documents/learning/rrweb/scripts/repl.ts:87:16
    at step (/Users/christianquiros/Documents/learning/rrweb/scripts/repl.ts:33:23)
    at Object.next (/Users/christianquiros/Documents/learning/rrweb/scripts/repl.ts:14:53)
    at fulfilled (/Users/christianquiros/Documents/learning/rrweb/scripts/repl.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➜  rrweb git:(master) 

Here is my npm version output in case useful:

npm version
{
  rrweb: '0.8.5',
  npm: '6.14.5',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.4.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '8.1.307.31-node.33',
  zlib: '1.2.11'
}

I am running macOS Catalina version 10.15.5 (19F101)

This project is awesome. Let me know if there is any extra info I can provide.

**Comment by Yuyz0112** [comment]
Looks like a puppeteer error that indicates you failed open github.com because of some network errors.

**Comment by cquirosj** [comment]
The same error happened independently of the site I tried with.

**Comment by cquirosj** [comment]
by puppeteer in package.json from version ^1.11.0 to version ^5.2.1 it worked.
