### ISSUE TITLE
ReferenceError: HTMLInputElement is not defined

### ISSUE THREAD

**Issue by jsilvia721** [rrweb-io/rrweb#34]
This might be a trivial question but I'm trying to require the `rrweb` package using:
```
const rrweb = require('rrweb');
```
but I'm getting the following error: 
```
ReferenceError: HTMLInputElement is not defined
    at Object.<anonymous> (/path/to/node_modules/rrweb/lib/rrweb.js:773:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Is this not how we should be importing the node package? It seems like this is expecting to be executed in a browser where `HTMLInputElement` is defined.

**Comment by Yuyz0112** [comment]
Yes, rrweb is a library works in browser.
