### ISSUE TITLE
rrweb里面npm install 的时候报错

### ISSUE THREAD

**Issue by liurongliurong** [rrweb-io/rrweb#675]
Error: 'createCache' is not exported by node_modules\rrweb-snapshot\es\rrweb-snapshot.js, imported by src\replay\index.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src\replay\index.ts (7:2)
5:   NodeType,
6:   BuildCache,
7:   createCache
     ^
8: } from 'rrweb-snapshot';
9: import * as mittProxy from 'mitt';
Error: 'createCache' is not exported by node_modules\rrweb-snapshot\es\rrweb-snapshot.js, imported by src\replay\index.ts
    at error (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:10059:16)
    at Module.traceVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:10444:29) 
    at ModuleScope.findVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:9227:39)
    at FunctionScope.findVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:3654:38)
    at ChildScope.findVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:3654:38)
    at FunctionScope.findVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:3654:38)
    at ChildScope.findVariable (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:3654:38)
    at Identifier.bind (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:4591:40)       
    at CallExpression.bind (C:\Users\10320\Desktop\rrweb-master\packages\rrweb\node_modules\rollup\dist\shared\rollup.js:2886:23)   

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rrweb@1.0.3 bundle: `rollup --config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rrweb@1.0.3 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\10320\AppData\Roaming\npm-cache\_logs\2021-08-24T07_54_53_998Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rrweb@1.0.3 prepack: `npm run bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rrweb@1.0.3 prepack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\10320\AppData\Roaming\npm-cache\_logs\2021-08-24T07_54_54_074Z-debug.log

**Comment by Yuyz0112** [comment]
Please try this

1. go to the project's root directory
2. run `yarn bootstrap`
3. run `yarn lerna run prepublish`

If all these three steps passed, all the packages should be built.

**Comment by Yuyz0112** [comment]
Feel free to reopen if there is any further information.
