### ISSUE TITLE
Console plugin stringify on error produces empty object

### ISSUE THREAD

**Issue by baransu** [rrweb-io/rrweb#814]
Executing following code

```js
try {
  throw new TypeError("my message");
} catch (error: unknown) {
  console.error(error);
}
```
produces following code in DevTools console (stack trace not relevant)
```
TypeError: my message
    at ThreadDevInfo.tsx:182:10
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushPassiveEffects (react-dom.development.js:23447:14)
    at react-dom.development.js:23324:11
```

but console plugin produces something like this
```
{
    "plugin": "rrweb/console@1",
    "payload": {
        "level": "error",
        "trace": [
            "https://jam.test:3000/src/components/Thread/ThreadDevInfo.tsx?t=1643212045995:136:15",
            "invokePassiveEffectCreate (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:16757:28)",
            "HTMLUnknownElement.callCallback2 (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:3671:22)",
            "Object.invokeGuardedCallbackDev (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:3696:24)",
            "invokeGuardedCallback (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:3730:39)",
            "flushPassiveEffectsImpl (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:16819:17)",
            "unstable_runWithPriority (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:346:20)",
            "runWithPriority$1 (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:8468:18)",
            "flushPassiveEffects (https://jam.test:3000/node_modules/.vite/chunk-BPLMWNAK.js?v=be0ca6f3:16723:22)"
        ],
        "payload": [
            "{}"
        ]
    }
}
```
as you see `payload` is equal to `{}` which means there were no keys found inside `Error`.

I found this code responsible for `Event` stringify:
https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/plugins/console/record/stringify.ts#L121-L133. Doing naive SO search I found this response: https://stackoverflow.com/questions/18277890/why-cant-i-see-the-keys-of-an-error-object which should work for `Error` as well.

**Comment by baransu** [comment]
Probably doing something like
```js
if(value instanceof Error) {
  return value.name + ": " + value.message
}
```
should be simple and effective solution 🤔

**Comment by LeeRayno** [comment]
1. 遇到了同样的 payload 为 {} 的 问题
2. 并且 上报的 trace 和 控制台显示的 错误堆栈不一致

控制台显示的错误堆栈如下：
```js
// react_devtools_backend.js:4061
TypeError: Cannot read properties of undefined (reading 'b')
    at Object.render [as renderFun] (index.tsx:66:18)
    at Object.Array.isArray.n.forEach.e.renderFun.e.render (EasyList.tsx:43:25)
    at render (132.13dc03038ae1d9aa5dee.js:1:7826)
    at _y (antd.4.16.13.min.js:23:704189)
    at Le (react-dom.17.0.2.production.min.js:100:3)
    at yh (react-dom.17.0.2.production.min.js:110:387)
    at Pj (react-dom.17.0.2.production.min.js:235:116)
    at di (react-dom.17.0.2.production.min.js:168:305)
    at Nj (react-dom.17.0.2.production.min.js:168:236)
    at sc (react-dom.17.0.2.production.min.js:168:96) 
```
而 回放 replay 拿到的 错误堆栈如下：
```js
{} // TIP: 这里 payload 为 {} 希望是 TypeError: Cannot read properties of undefined (reading 'b')
   at Ye (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:141:274)
   at Mh.c.callback (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:141:448)
   at dh (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:80:101)
   at Bj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:145:119)
   at Qj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:176:361)
   at unstable_runWithPriority (https://s3-gz01.didistatic.com/wujie-resource/lib/react.17.0.2.production.min.js:24:26)
   at Za (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:73:8)
   at eb (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:170:163)
   at gf (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:162:317)

```

TypeError 测试数据：
```json
{
  "message": "Cannot read properties of undefined (reading 'b')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'b')\n    at Object.render [as renderFun] (https://boss-sim.chengxinyouxuan.com/mendian-micro-promise-new/20220209_l_error_log_test/static/js/promiseTools.5e448812.chunk.js:1:440040)\n    at Object.Array.isArray.n.forEach.e.renderFun.e.render (https://boss-sim.chengxinyouxuan.com/mendian-micro-promise-new/20220209_l_error_log_test/static/js/promiseTools.5e448812.chunk.js:1:408427)\n    at render (https://s3-gz01.didistatic.com/default/@didi/cx-xms-compo/sim/20220129-113855/132.13dc03038ae1d9aa5dee.js:1:7826)\n    at _y (https://s3-gz01.didistatic.com/wujie-resource/lib/antd.4.16.13.min.js:23:704189)\n    at Le (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:100:3)\n    at yh (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:110:387)\n    at Pj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:235:116)\n    at di (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:305)\n    at Nj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:236)\n    at sc (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:96)"
}


```
![image](https://user-images.githubusercontent.com/18265584/153203718-5cad8e92-1351-407f-b809-e72108ec1898.png)
![image](https://user-images.githubusercontent.com/18265584/153204523-92ae59b2-0e72-4af2-b6b8-ea5d60d44739.png)

@Yuyz0112  有时间了帮忙看下

**Comment by LeeRayno** [comment]
@Mark-Fenng 错误堆栈 trace 好像解析也有问题了，和控制台显示的不一样，可以用上面的测试数据测试一下

**Comment by Mark-Fenng** [comment]
@LeeRayno 之前只会记录console.error调用处的trace，而错误本身的trace没有被记录。 可否试一试https://github.com/rrweb-io/rrweb/commit/611a8c6d0cb10a840b14105e16472171fc88dc28 这个是否能解决你的问题

**Comment by LeeRayno** [comment]
> 
好的。谢谢！还有另外一种办法不知可行不
将错误本身的 trace 插入到 trace 前面了

```js
// fake error
const args = [
  {
    "message": "Cannot read properties of undefined (reading 'b')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'b')\n    at Object.render [as renderFun] (https://boss-sim.chengxinyouxuan.com/mendian-micro-promise-new/20220209_l_error_log_test/static/js/promiseTools.5e448812.chunk.js:1:440040)\n    at Object.Array.isArray.n.forEach.e.renderFun.e.render (https://boss-sim.chengxinyouxuan.com/mendian-micro-promise-new/20220209_l_error_log_test/static/js/promiseTools.5e448812.chunk.js:1:408427)\n    at render (https://s3-gz01.didistatic.com/default/@didi/cx-xms-compo/sim/20220129-113855/132.13dc03038ae1d9aa5dee.js:1:7826)\n    at _y (https://s3-gz01.didistatic.com/wujie-resource/lib/antd.4.16.13.min.js:23:704189)\n    at Le (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:100:3)\n    at yh (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:110:387)\n    at Pj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:235:116)\n    at di (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:305)\n    at Nj (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:236)\n    at sc (https://s3-gz01.didistatic.com/wujie-resource/lib/react-dom.17.0.2.production.min.js:168:96)"
  }
]
// https://github.com/rrweb-io/rrweb/blob/1935bf606fb57dcda991006f4effed50c351053b/packages/rrweb/src/plugins/console/record/index.ts#L169

const errTrace = args?.reduce((acc, cur) => {
  acc.push(...cur?.stack?.split('\n    '));
  return acc;
}, []);

// other code ...
cb({
    level,
    trace: [...errTrace, ...trace],
    payload,
});

```

**Comment by Mark-Fenng** [comment]
@LeeRayno 数据结构的trace是为了存储console的调用位置的stack的，最好不要往其中塞入特殊的复杂的含义

**Comment by LeeRayno** [comment]
我们这个一般多久发一版了。希望能尽快发一版，感谢！
