### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb#88]
Hi !

I got the following exception while replaying a session recorded on one of my website.

<img width="1376" alt="issue" src="https://user-images.githubusercontent.com/7370867/60961822-42ac4800-a30d-11e9-95ec-eec9975d426f.png">

During the session, it crashed when the user was interacting with some dynamic selects / dropdowns.

Have you already seen this kind of errors?

PS: I can't post the events log due to privacy rules

**Comment by Yuyz0112** [comment]
If this happens with version 0.7.16, then it may be a new bug.

Could you tell me which select component is this project using? Maybe I can try to reproduce it.

**Comment by xavier-heysch** [comment]
There is no custom component for the selects.

They are just dynamic dropdowns with live changes handled by AngularJS (1.6.10)

**Comment by s-jakob** [comment]
@Yuyz0112 i have the same problem. It is only happening on one specific page and only with the safari browser (mobile and desktop). I think there is maybe an DOM change which the recorder didn't detect.
I can try to get a recording of it, if you need id.

**Comment by Juice10** [comment]
Copied from #306.

In some cases when `applyMutation` removes a node, the parent of that node is not attached to the document. This triggers the following error `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

## Expected behaviour
No error should happen

## To reproduce
1. `git clone git@github.com:juice10/rrweb-player-1.git`
2. `npm install`
3. `npm start`
4. Open [http://localhost:1234](http://localhost:1234)
5. Seek to around the 23 second or 26 second mark and let it play for a couple seconds, error will trigger: <img width="286" alt="image" src="https://user-images.githubusercontent.com/4106/91184454-f24ca100-e6ec-11ea-8bf9-66e469f99c3f.png">

# Additional information

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4106/91185254-de556f00-e6ed-11ea-9a2b-3ac7ca503a78.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/4106/91185362-0513a580-e6ee-11ea-9bf7-39f3e01eb1d4.png">


The error isn't triggered when seeking (`isSync == true`) past the event.
The error also isn't triggered if playing from the very start.

Based off of https://github.com/rrweb-io/rrweb/issues/285#issuecomment-678808349 & https://github.com/rrweb-io/rrweb/issues/285#issue-679841740

## Example event triggering failure
```json
{"source":0,"texts":[{"id":3033,"value":"\n/* sc-component-id: sc-global-2139370859 */\n.intercom-messenger-frame{left:0.5rem !important;bottom:4.25rem !important;}"}],"attributes":[],"removes":[{"parentId":99,"id":2635}],"adds":[{"parentId":99,"nextId":107,"node":{"type":3,"textContent":"\n/* sc-component-id: sc-global-2139370859 */\n.intercom-messenger-frame{left:0.5rem !important;bottom:4.25rem !important;}","isStyle":true,"id":3033}}]}
```

View [all events](https://github.com/Juice10/rrweb-player-1/blob/master/src/response.js).

**Comment by codetaintian** [comment]
@Yuyz0112 Hi, I've been having the same problem recently.Can you help me out？

**Comment by Juice10** [comment]
More related issues: https://github.com/rrweb-io/rrweb/issues/376 https://github.com/rrweb-io/rrweb/issues/337

**Comment by Kimmax** [comment]
We're also hitting this in #365

**Comment by NulSEO** [comment]
... And still no response. I don't get that. People have opened issues regarding these problems before. @Yuyz0112 requested event data - they never replied. Now there's a bunch of event data and the issues are just being ignored. ¯\_(ツ)_/¯ (#337 #365 #376)

**Comment by Yuyz0112** [comment]
Hi @NulSEO 

Actually, this error message is very general and most of the events are causing by different reasons. @Juice10 pointed out a way to reproduce it which is technically right, but I believe are not related to the problems you are facing.

I've done some debug on #337, #365, and #376, most of them are causing by some un-confirmed usage of rrweb, like merging different sessions into one.

So please upload your events or reproducible link for debugging. The other one's report may not help fix your problem.

**Comment by goldy-13** [comment]
I am having error while replaying events DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at appendNode (http://localhost:3000/static/js/0.chunk.js:150183:76)
    at http://localhost:3000/static/js/0.chunk.js:150194:7
    at Array.forEach (<anonymous>)
    at Replayer.applyMutation (http://localhost:3000/static/js/0.chunk.js:150193:12)
    at Replayer.applyIncremental (http://localhost:3000/static/js/0.chunk.js:149790:16)
    at castFn (http://localhost:3000/static/js/0.chunk.js:149494:17)
    at wrappedCastFn (http://localhost:3000/static/js/0.chunk.js:149556:9)
    at _loop_1 (http://localhost:3000/static/js/0.chunk.js:150796:13)
    at play (http://localhost:3000/static/js/0.chunk.js:150812:13)
    at http://localhost:3000/static/js/0.chunk.js:144542:17

**Comment by goldy-13** [comment]
@Juice10  I am getting DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method. while seeking video in some recordings. Could you please help me out

**Comment by Juice10** [comment]
@goldy-13 I was not able to fix my own issue but I’m happy to help if I can. What version of rrweb or rrweb-player are you using? Could you create a gist of your events?

**Comment by goldy-13** [comment]
> @goldy-13 I was not able to fix my own issue but I’m happy to help if I can. What version of rrweb or rrweb-player are you using? Could you create a gist of your events?

I am using rrweb 0.9.14

**Comment by Tang-jianchao** [comment]
mark

**Comment by heyitsnovi** [comment]
Same issues goes to me. any updates regarding this one?

**Comment by Mark-Fenng** [comment]
@heyitsnovi Like Yuyz0112 said, this error message is very general and most of the events are causing by different reasons. If you are facing the same errors, please upload your events to help us figure out the root cause.

**Comment by heyitsnovi** [comment]
> @heyitsnovi Like Yuyz0112 said, this error message is very general and most of the events are causing by different reasons. If you are facing the same errors, please upload your events to help us figure out the root cause.

here's the sample event json link:
https://gist.github.com/heyitsnovi/c31fc044fb7c85945fc4bae79433ec4b
